trigger: none

parameters:
  - name: environment
    displayName: 'Demo Environment'
    type: string
    default: 'demo-red'
    values:
      - demo-red
      - demo-blue

pr: none

stages:
- stage: Deploy-red
  jobs:

  - deployment: Deploy to demo-red
    environment: demo-red
    timeoutInMinutes: 120
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
        runOnce:    #rolling, canary are the other strategies that are supported
          deploy:
            steps:
            - template: templates/deploy-template.yml

- stage: Deploy-blue
  jobs:

  - deployment: Deploy to demo-blue
    environment: demo-blue
    timeoutInMinutes: 120
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
        runOnce:    #rolling, canary are the other strategies that are supported
          deploy:
            steps:
            - template: templates/deploy-template.yml