trigger: none

parameters:
  - name: Demo
    displayName: 'Select Demo Environment'
    type: string
    default: 'red'
    values:
      - red
      - blue

pr: none

stages:
- stage: DeployDemoEnvironment
  displayName: 'Deploy to $(Demo)'

  jobs:

  - deployment: Deploy
    environment: demo-$(Demo)
    timeoutInMinutes: 120
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
        runOnce:    #rolling, canary are the other strategies that are supported
          deploy:
            steps:
            - template: templates/deploy-template.yml